const lang = {
    en: {
      language: "Englisvzdvh",
      search: "Search",
      gptSearchPlaceHolder: "What would you like to watch today ?",
      signIn: "Sign In",
      signUp: "Sign Up",
      fullName: "Full Name",
      email: "Email Address",
      password: "Password",
      createPwd: "Create New Password",
      remember: "Remember Me",
      needHelp: "Need Help ?",
      newPatient: "New Patient?",
      signUpNow: "Sign Up Now.",
      signInNow: "Sign In Now.",
      alreadyUser: "Already a user?",
      dob: "Date Of Birth",
      address:"Address",
      patient:"Patient",
      practitioner:"Practitioner",
      doctor:"Doctor",
      admin:"Admin"

      
    },
    hi: {
      search: "खोजे",
      gptSearchPlaceHolder: "आज आप क्या देखना चाहेंगे ?",
      signIn: "साइन इन करें",
      signUp: "साइन अप करें",
      fullName: "पूरा नाम",
      email: "ईमेल एड्रेस",
      password: "पासवर्ड",
      createPwd: "नया पासवर्ड बनाएं",
      remember: "याद रखें",
      needHelp: "आपको मदद चाहिए?",
      newToNetflix: "Netflix पर नए हैं?",
      signUpNow: "अभी साइन अप करें",
      signInNow: "अभी साइन इन करें",
      alreadyUser: "Netflix पर पहले से हैं?",
    },
    sp: {
      search: "búsqueda",
      gptSearchPlaceHolder: "¿Qué te gustaría buscar hoy?",
      signIn: "Iniciar sesión",
      signUp: "Inscribirse",
      fullName: "Nombre completo",
      email: "Dirección de correo electrónico",
      createPwd: "Crear nueva contraseña",
      password: "Contraseña",
      remember: "Acuérdate de mí",
      needHelp: "¿Necesitas ayuda?",
      newToNetflix: "¿Nuevo en Netflix?",
      signUpNow: "Regístrate ahora.",
      signInNow: "Regístrate.",
      alreadyUser: "¿Ya eres usuario?",
    },
    fr: {
      search: "recherche",
      gptSearchPlaceHolder: "Qu’aimeriez-vous regarder aujourd’hui ?",
      signIn: "Se connecter",
      signUp: "S'inscrire",
      fullName: "Nom et prénom",
      email: "Adresse e-mail",
      password: "Mot de passe",
      createPwd: "Créer un nouveau mot de passe",
      remember: "Souviens-toi de moi",
      needHelp: "Besoin d'aide?",
      newToNetflix: "Nouveau sur Netflix?",
      signUpNow: "S'inscrire maintenant.",
      signInNow: "Connectez vous maintenant.",
      alreadyUser: "Déjà utilisateur?",
    },
  };
  
  export default lang;
  